Add and configure Serverless plugins to app.
svetlanagorchanina/nodejs-aws-fe pull request #1
Opened 2020-10-18 12:24 UTC by svetlanagorchanina

2020-10-26 14:37 UTC, NikaOrl requested changes
Please, follow convention for commit messages: https://docs.rs.school/#/git-convention and convention for PR description: https://docs.rs.school/#/stage2?id=Требования-к-pull-request-pr

2020-10-26 14:37 UTC, NikaOrl commented on .gitignore
> +.serverless
.serverless already exists in .gitignore

2020-10-26 14:37 UTC, NikaOrl commented on package.json
> +    "deploy:s3": "serverless client deploy --no-config-change --no-policy-change --no-cors-change",
duplicates 'client:deploy' script

2020-10-26 14:37 UTC, NikaOrl commented on package.json
> +    "build:deploy": "npm run build && npm run deploy:s3",
duplicates 'client:build:deploy' script

2020-10-26 14:37 UTC, NikaOrl commented
Score: 5/5

2020-10-27 15:52 UTC, svetlanagorchanina commented
@NikaOrl Good points, thanks for great review!

2020-10-29 17:47 UTC, merged